### ISSUE TITLE
Is this project dead? Can anyone recommend a similar PHP IDE for Linux? 

### ISSUE THREAD

**Issue by rafal-1990** [eclipse/pdt#141]
Hello,
I wonder if this project is dead because PHP 8 is still not supported (and #95 is not really answered) after so long and in general there were no commits for a long time.

I assume, that the validation error `Constant expression contains invalid operations` in the following line appears because of missing PHP 8 support:

    function formatDate($IntlDateFormatter=new IntlDateFormatter('de_DE',IntlDateFormatter::FULL,IntlDateFormatter::FULL,'Europe/Berlin',IntlDateFormatter::GREGORIAN)) {

This code works on my server with PHP 8.1 without problems, so the syntax is correct and I expect my IDE not to display errors that are not errors.

Therefore, I am now looking for another IDE for PHP development under Linux (preferably with few dependencies and available as a .deb package, Linux binary or Java-based).
Can anyone recommend an alternative for Eclipse PDT (which supports the latest PHP version and is actively developed further)?

**Comment by troizet** [comment]
You can try [netbeans](https://github.com/apache/netbeans).

**Comment by ibakirov** [comment]
Visual Studio Code
Brackets
Komodo IDE
bluefish
Aptana Studio

**Comment by zulus** [comment]
not dead, at least as long as I live ;)

anyway, due my personal changes, everything was postponed...
but, because php8 become critical in my company, I'm trying to prepare at least basic support ASAP

**Comment by tbl0605** [comment]
David,
Glad to hear you're still working on PDT :)
I'll try to help again, once you've posted some new code. It's been a long
time since I've coded in Java now lol
My personal and professional obligations have taken me to other horizons,
but PDT remains one of the most interesting projects to which I have
contributed :)

Le mar. 13 sept. 2022 à 12:08, Dawid Pakuła ***@***.***> a
écrit :

**Comment by nabice** [comment]
@zulus 
How's it going so far? I'm interested in the Parser part, if that part is done, can you commit it first? If not, I will try to implement it with your guidance.

**Comment by rafal-1990** [comment]
Sorry for not replying sooner.

@troizet Thanks for the tip with Netbeans. It actually makes a good impression, but what I don't like is that it takes about 830 MB of disk space. I already found the 580 MB of Eclipse with PDT quite large.

@ibakirov From your list, Komodo IDE looks like the best alternative. With about 254 MB it is even relatively small and the functions are actually sufficient for my purpose. What I don't like is that you have to register (even though it's free).

Before I move on to Netbeans or Komodo IDE, I think I'll wait for a new version of Eclipse PDT after all. It's nice to hear that the main developer is still interested in further development and I hope we can expect PHP 8 support soon.

**Comment by ibakirov** [comment]
@rafal-1990 There is always time to wait, but you may have to wait a very long time :)

**Comment by spider4216** [comment]
Write my code in eclipse with pdt huge amount of time. Hope we'll see pdt8 soon. @zulus do you have [opencollective](https://opencollective.com/) or something like that? Maybe PDT Community will be able to contribute financially

**Comment by Medelpunkten** [comment]
> not dead, at least as long as I live ;)
> 
> anyway, due my personal changes, everything was postponed... but, because php8 become critical in my company, I'm trying to prepare at least basic support ASAP

I have followed this interesting thread for over a month now. 
For me, I feel the time is now -  approximately one month until support of PHP7.4 ends. I have used Eclipse PDT since 2014, and I am super happy about the program! But… Now I am getting really worried about my PHP7.4 web application. The application is crucial for the International Medical Device business. (I perhaps can explain later...)
Please, give me an advice. Is it urgent for me to abandon Eclipse PDT. Will there be a solution ready, and have a chance to adapt tested code to PHP8, within this timeframe?

**Comment by werc** [comment]
@Medelpunkten Honestly ... I would not expect any progress. I had to change IDE and I'm now on PhpStorm.

**Comment by pounard** [comment]
I'm really stubborn and continue to use Eclipse, but as soon as I open a PHP 8 file, I'm forced to use it as a simple notepad because the parser doesn't understand the code anymore. Please @zulus, do you have at least some kind of deadline for PHP 8 support, or will I be forced to leave as well ? I love Eclipse and PDT, I really want it to continue to exist, and really want to continue to use it !

**Comment by nabice** [comment]
I recently made some changes to the parser to support 8.0 and 8.1.
https://github.com/nabice/pdt

But I don't know what to do next.

**Comment by stanolacko** [comment]
Cool! I suppose it's working. Maybe it made a howto, how can others compile
your fork and use it in their Eclipse. It will be helpful.

**Comment by pounard** [comment]
MOAR ! @nabice very nice, I agree that a small tuto to compile the plugin would be a nice to have, I'd really love to test it.

**Comment by nabice** [comment]
It's still far from complete. Only the part that converts the source code to AST is implemented. Others such as highlighting, type resolving, etc., I am not familiar with the project so I couldn't get it done.

**Comment by stanolacko** [comment]
Believe me, also these changes can help those who need to work with PHP 8.x
files in PDT.

**Comment by pounard** [comment]
> It's still far from complete. Only the part that converts the source code to AST is implemented

That's already huge.

**Comment by waynebeaton** [comment]
> But I don't know what to do next.

Next steps:

Sign the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) and send a pull request.
