### ISSUE TITLE
linter complains about html script async attribute

### ISSUE THREAD

**Issue by divinity76** [eclipse/pdt#92]
**Describe the bug**
when writing `<?php ?><script async src="whatever"></script>` , the linter says `Undefined attribute value().`
(the screenshot below probably explains it best)

**Describe the eclipse environment**
Eclipse Version: 2020-06 (4.16.0)
Build id: 20200615-1200

PHP Development Tools (PDT) version 7.2.0.202005271851 org.eclipse.php.feature.group	Eclipse PDT

**Describe your system**
 - OS: Xubuntu Linux 18.04

**To Reproduce**
1. create a new file with the content

```php
<?php ?>
<!DOCTYPE HTML>
<html>
<head>
<script async src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
</head>
<body></body></html>
```

2. check for linter errors on the <script> line
3. See error

**Expected behavior**
no error, async is a valid attribute per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

**Screenshots**
![image](https://user-images.githubusercontent.com/1874996/93824852-6fbfee80-fc64-11ea-989b-a62f02576c2d.png)

**Additional context**

**Comment by cendern** [comment]
I'm pretty sure the responsible code lives in [eclipse/webtools.sourceediting](https://github.com/eclipse/webtools.sourceediting/blob/62e575d162faf85b4b63833b193451f8da5085c5/web/bundles/org.eclipse.wst.html.core/src/org/eclipse/wst/html/core/internal/contentmodel/HTML5AttributeCollection.java#L1121), not eclipse/pdt, so this issue is going to get closed for that reason. Please consider filing the same issue in eclipse/webtools.sourceediting instead. FYI I'm not an admin, I just had the same issue (in plain Eclipse, not PDT) and looked to see if someone had already reported it.

**Comment by zulus** [comment]
This require WTP drop that is planed for this year. Closing for now, we have a lot of WTP-related issues
